[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 1_000_000

ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./out/" },
    { access = "read", path = "../prediction-contracts/out/" },
]

[fmt]
line_length = 120
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config 